### ISSUE TITLE
Calling updateUser() throws Call to undefined method GuzzleHttp\Utils::jsonEncode()

### ISSUE THREAD

**Issue by igittigitt** [MohammadWaleed/keycloak-admin-client#83]
I've fetched the latest master (also develop) but run into that error when trying to use the updateUser() endpoint of the API
```
PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::jsonEncode() in /systems/test/lib/php/Keycloak/keycloak-admin-client/vendor/guzzlehttp/guzzle-services/src/RequestLocation/JsonLocation.php:51
Stack trace:
#0 /systems/test/lib/php/Keycloak/keycloak-admin-client/vendor/guzzlehttp/guzzle-services/src/Serializer.php(92): GuzzleHttp\Command\Guzzle\RequestLocation\JsonLocation->visit()
#1 /systems/test/lib/php/Keycloak/keycloak-admin-client/vendor/guzzlehttp/guzzle-services/src/Serializer.php(62): GuzzleHttp\Command\Guzzle\Serializer->prepareRequest()
#2 /systems/test/lib/php/Keycloak/keycloak-admin-client/vendor/guzzlehttp/command/src/ServiceClient.php(195): GuzzleHttp\Command\Guzzle\Serializer->__invoke()
#3 /systems/test/lib/php/Keycloak/keycloak-admin-client/vendor/guzzlehttp/command/src/ServiceClient.php(172): GuzzleHttp\Command\ServiceClient->transformCommandToRequest()
#4 [internal function]: GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}()
#5 /systems/cue-a in /systems/test/lib/php/Keycloak/keycloak-admin-client/vendor/guzzlehttp/guzzle-services/src/RequestLocation/JsonLocation.php on line 51
```
I found the request method jsonEncode() in the utils.php file, so no clue why it fails
grep -r jsonEncode *
`/systems/test/lib/php/Keycloak/keycloak-admin-client/vendor/guzzlehttp/guzzle/src/Utils.php:    public static function jsonEncode($value, int $options = 0, int $depth = 512): string
`

**Comment by igittigitt** [comment]
So sorry, it was my own fault! I've missed that another tool with an older GuzzleHttp dependency (6.x) was loaded before loading keycloak-admin-client lib. This preventes keycloak-client from loading the correct GuzzleHttp (7.x) afterwards. The old Guzzle lib is missing the jsonDecode() function and so the error above arises.
